<template>
    
        <div class="row">
            
            <hr>
            <img style="float: right; padding-top: 10px;" src='../../resources/img/logo_FOREO.svg' alt="Foreo logo">
            <p class="small-text">&copy; 2018 FILIP KAPUSTA ALL RIGHTS RESERVED</p>
        </div> 
    
</template>
<style>
    .small-text{
        font-size: 60%;
        padding-top: 15px;
        font-weight: 400;
    }
</style>
